### ISSUE TITLE
Consolidate and Clean-up Mobile tags

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#328]
Over the years, we used A LOT of tags related to Mobile.
It would be good to try to consolidate these and fix the ones that might be broken or not working in or favor.

There are currently `~1370` uses of ` - mobile` across `551` files in our project.

The mobile articles usually contain multiple tags:

```
  - mobile
  - mobile apps
  - mobile gov

```

**Comment by jeremyzilar** [comment]
Here are the existing mobile tags.
@ToniBonittoGSA which should we keep?

```
mobile:
  display_name: "Mobile"
mobile-app-development-program:
  display_name: "Mobile App Development Program"
mobile-apps:
  display_name: "Mobile Apps"
mobile-code-catalog:
  display_name: "Mobile Code Catalog"
mobile-first:
  display_name: "Mobile First"
mobile-friendly:
  display_name: "Mobile Friendly"
mobile-gov:
  display_name: "Mobile Gov"
mobile-gov-community-of-practice:
  display_name: "Mobile Gov Community Of Practice"
mobile-gov-experience:
  display_name: "Mobile Gov Experience"
mobile-testing:
  display_name: "Mobile Testing"
mobile-user-experience-guidelines:
  display_name: "Mobile User Experience Guidelines"
mobile-ux-guideline-1:
  display_name: "Mobile UX Guideline 1"
mobile-ux-guideline-2:
  display_name: "Mobile UX Guideline 2"
mobile-ux-guideline-3:
  display_name: "Mobile UX Guideline 3"
mobile-ux-guideline-4:
  display_name: "Mobile UX Guideline 4"
mobile-ux-guideline-5:
  display_name: "Mobile UX Guideline 5"
mobile-ux-guideline-6:
  display_name: "Mobile UX Guideline 6"
mobilegov:
  display_name: "Mobilegov"
```

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA — which of these should we keep?

```
mobile:
  display_name: "Mobile"
mobile-app-development-program:
  display_name: "Mobile App Development Program"
mobile-apps:
  display_name: "Mobile Apps"
mobile-code-catalog:
  display_name: "Mobile Code Catalog"
mobile-first:
  display_name: "Mobile First"
mobile-friendly:
  display_name: "Mobile Friendly"
mobile-gov:
  display_name: "Mobile Gov"
mobile-gov-community-of-practice:
  display_name: "Mobile Gov Community Of Practice"
mobile-gov-experience:
  display_name: "Mobile Gov Experience"
mobile-testing:
  display_name: "Mobile Testing"
mobile-user-experience-guidelines:
  display_name: "Mobile User Experience Guidelines"
mobile-ux-guideline-1:
  display_name: "Mobile UX Guideline 1"
mobile-ux-guideline-2:
  display_name: "Mobile UX Guideline 2"
mobile-ux-guideline-3:
  display_name: "Mobile UX Guideline 3"
mobile-ux-guideline-4:
  display_name: "Mobile UX Guideline 4"
mobile-ux-guideline-5:
  display_name: "Mobile UX Guideline 5"
mobile-ux-guideline-6:
  display_name: "Mobile UX Guideline 6"
mobilegov:
  display_name: "Mobilegov"
```
