### ISSUE TITLE
New Event: An Around the World Recap: PLAIN Monthly Meeting

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#66]
```
---
slug: an-around-world-recap-plain-monthly-meeting
title: 'An Around the World Recap PLAIN Monthly Meeting'
summary: 'In this online event, PLAIN co-chairs will provide a recap of international plain language initiatives discussed at the 2017 Plain Language Association International conference in Graz, Austria'
featured_image:
  uid: tile-3
  alt: 'decorative image'
event_type: online
date: 2017-10-11 14:00:00 -0400
end_date: 2017-10-11 15:00:00 -0400
event_organizer: DigitalGov University
host: PLAIN
registration_url: https://www.eventbrite.com/e/an-around-the-world-recap-plain-monthly-meeting-registration-38539458558
youtube: https://www.youtube.com/watch?v=3FKyVeipMss
---
```

In this month's meeting, the [Plain Language Action and Information Network (PLAIN)](https://www.digitalgov.gov/communities/plain-language-community-of-practice/) co-chairs will provide a recap of international plain language initiatives discussed at the 2017 Plain Language Association International conference in Graz, Austria.
 
The second Wednesday of every month, PLAIN hosts a monthly meeting from 2-3 p.m. Hosted by Digital Gov, the meetings are recorded and posted to Digital Gov's YouTube channel.

In addition to addressing timely topics, like science communications and health literacy, typical discussions include: plain language training; hands-on editing exercises; how to write for web and social media; and content strategy.
