### ISSUE TITLE
Make it easier to tag pages on digital.gov

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#710]
## As an editor, I want to be able to easily add/edit tags on a page on digital.gov.
At the moment, that process is not easy. In fact, it is really hard.

There are over **563 tags** on digital.gov https://github.com/GSA/digitalgov.gov/blob/master/data/tag.yml and knowing the exact names of those tags, and their slugs for using them in the front-matter of blog posts is very difficult work.

```
workflows:
  display_name: "Workflows"
world-bank:
  display_name: "World Bank"
yelp:
  display_name: "Yelp"
youtube:
  display_name: "Youtube"
zero-ui:
  display_name: "Zero UI"
```

In addition, we have over 2500 pages on digital.gov, and we would like to be able to tag more of our pages, but at this time, that process is too hard to do for a single page.
